apiVersion: v1
kind: Namespace
metadata:
  name: grafana-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana-ns
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service.prometheus-ns.svc.cluster.local:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: grafana-ns
data:
  prometheus-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Prometheus Stats",
        "tags": ["prometheus"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Uptime",
            "type": "singlestat",
            "targets": [
              {
                "expr": "up",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                }
              }
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "templating": {
          "list": []
        },
        "annotations": {
          "list": []
        },
        "refresh": "5s",
        "schemaVersion": 27,
        "version": 0,
        "links": []
      }
    }
  argocd-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "ArgoCD Overview",
        "tags": ["argocd"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "ArgoCD Targets Up",
            "type": "table",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "up{job=~\"argocd.*\"}",
                "refId": "A"
              }
            ]
          },
          {
            "id": 2,
            "title": "ArgoCD Sync Total",
            "type": "graph",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "argocd_app_sync_total",
                "refId": "A"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "templating": {
          "list": []
        },
        "annotations": {
          "list": []
        },
        "refresh": "30s",
        "schemaVersion": 27,
        "version": 0,
        "links": []
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: grafana-ns
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'prometheus'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana-ns
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer