apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kali-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: kali-vm
    spec:
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 6Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/kali:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: kali
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQREPLACE_WITH_YOUR_KEY
              package_update: true
              packages:
                - kali-desktop-xfce
                - xrdp
              runcmd:
                - systemctl enable xrdp
                - systemctl start xrdp
                - adduser xrdp ssl-cert